name: 'js-check-update-action'
description: 'check package.json'

inputs:
  TOKEN_APP:
    description: 'token app'
    required: true
    default: 'World'
  MAIL_USERNAME:
    description: 'user mail'
    required: true
    default: 'World'
  MAIL_PASSWORD:
    description: 'mail password'
    required: true
    default: 'World'
  MAIL_TO:
    description: 'mail to'
    required: true
    default: 'World'
    
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i -g yarn
        shell: bash
      - run: yarn
        shell: bash
      - run: yarn yarn-upgrade-minor --non-interactive > console.log
        shell: bash
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      - name: execute py script 
        run: |
          python replace.py
        shell: bash
      - uses: actions-js/push@master
        with:
          github_token: ${{ inputs.TOKEN_APP }}
          empty: false
          branch: master
          message: 'update lib via action'
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ inputs.MAIL_USERNAME}}
          password: ${{ inputs.MAIL_PASSWORD}}
          subject: ${{github.repository}} Github Actions job result
          to: ${{ inputs.MAIL_TO}}
          from: GIT
          secure: true
          body: Build job of ${{github.repository}} completed successfully!
          ignore_cert: true
          attachments:  console.log, package.json
          priority: low
